language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

sudo: false

addons:
  apt:
    packages:
    - gfortran

install:
  - pip install --no-deps .

script:
  - cd test
  - python test.py
